# permissions for end users to edit hivemetastores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hivemetastore-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hive-metastore-operator
    app.kubernetes.io/part-of: hive-metastore-operator
    app.kubernetes.io/managed-by: kustomize
  name: hivemetastore-editor-role
rules:
- apiGroups:
  - stack.zncdata.net
  resources:
  - hivemetastores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.zncdata.net
  resources:
  - hivemetastores/status
  verbs:
  - get
