apiVersion: stack.zncdata.net/v1alpha1
kind: HiveMetastore
metadata:
  labels:
    app.kubernetes.io/name: hivemetastore
    app.kubernetes.io/instance: hivemetastore-sample
    app.kubernetes.io/part-of: hive-metastore-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hive-metastore-operator
  name: hivemetastore-sample
spec:
  service:
    port: 9083
    type: ClusterIP
  image:
    repository: quay.io/plutoso/hive
    tag: 4.0.0-beta-1
    pullPolicy: IfNotPresent
  roleConfig:
    replicas: 2
    config:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
      database:
        reference: "database-sample"
  #    s3:
  roleGroups:
    default:
      replicas: 1
      config:
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        s3:
          maxConnect: 50
          pathStyle_access: true
          bucket:
            reference: "s3bucket-sample"
      matchLabels:
        app: foo
    foo:
      replicas: 1
      config:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      matchLabels:
        app: foo
  securityContext:
    runAsUser: 1000
    fsGroup: 1000